FROM docker.io/rust:1.62-alpine as BUILDER

WORKDIR /app

RUN apk add musl-dev libc-dev postgresql-dev

RUN cargo install diesel_cli --no-default-features --features "postgres"

CMD ["/app/diesel", "migration", "run"]
