name: Publish Code Coverage

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Cinstrument-coverage
  DATABASE_URL: postgres://postgres:postgres@localhost:5433/postgres

jobs:
  gen:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libpq-dev capnproto
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        default: true
        components: llvm-tools-preview
    - name: Setup Cache
      uses: Swatinem/rust-cache@v1
    - name: Download grcov
      run: curl -L https://github.com/mozilla/grcov/releases/download/v0.8.11/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar xjf -
    - name: Get Diesel Cli
      run: cargo install diesel_cli
    - name: Migrate DB
      run: diesel migration run
    - name: Run tests
      run: LLVM_PROFILE_FILE="ipv8-auth-%p-%m.profraw" cargo test
    - name: Generate report file
      run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Publish to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./lcov.info
        flags: unittests
        name: github-actions-publish
        fail_ci_if_error: true
        verbose: true
